baseURL = '/'
languageCode = 'en-us'
title = 'Prosphora help'
contentDir = "content"
enableEmoji = true

defaultContentLanguage = 'en'
[languages]
    [languages.en]
        title = "Lotus Docs Example Site"
        languageName = "English"
        weight = 10
#    [languages.fr]
#        title = "Lotus Docs Exemple de Site"
#        languageName = "Français"
#        contentDir = "content/fr"
#        weight = 20
#    [languages.de]
#        title = "Lotus Docs Beispiel Site"
#        languageName = "Deutsch"
#        contentDir = "content/de"
#        weight = 30

[module]
# uncomment line below for temporary local development of module
# or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [module.hugoVersion]
        extended = true
        min = "0.100.0"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.tableOfContents]
        endLevel = 3
        startLevel = 1
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
# [markup.highlight]
#   codeFences = false # disables Hugo's default syntax highlighting
# [markup.goldmark.parser]
#   [markup.goldmark.parser.attribute]
#     block = true
#     title = true


[menu]
  [[menu.primary]]
     name  = "Docs"
     url = "docs/"
     identifier = "docs"
     weight = 10

# [[menu.primary]]
#     name  = "Showcase"
#     url = "/showcase"
#     identifier = "showcase"
#     weight = 20

 [[menu.primary]]
     name  = "Community"
     url = "https://www.svetek.com"
     identifier = "community"
     weight = 30